name: cabconsumidor
description: A new Flutter project.

publish_to: 'none'

version: 1.0.1+11

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  brasil_fields: ^1.13.1
  cloud_firestore: ^4.3.1
  cupertino_icons: ^1.0.2
  custom_navigation_bar: ^0.8.2
  debounce_throttle: ^2.0.0
  dio: ^5.2.1+1
  firebase_auth: ^4.6.3
  firebase_core: ^2.2.0
  firebase_core_platform_interface: 4.8.0
  firebase_messaging: ^14.6.3
  firebase_storage: ^11.2.3
  flutter:
    sdk: flutter
  flutter_barcode_scanner: ^2.0.0
  flutter_dotenv: ^5.1.0
  flutter_dropdown_search: ^0.0.4
  flutter_launcher_icons: ^0.13.1
  flutter_masked_text2: ^0.9.1
  flutter_modular: ^5.0.3
  flutter_svg: ^1.0.3
  flutter_triple: ^2.0.1
  google_fonts: ^4.0.0
  http: ^0.13.0
  image_picker: ^0.8.9
  intl: ^0.18.1
  location: ^5.0.3
  lottie: ^2.4.0
  mask_text_input_formatter: ^2.4.0
  permission_handler: ^10.4.3
  qr_flutter: ^4.1.0
  shared_preferences: ^2.1.1
  shimmer: ^3.0.0
  url_launcher: ^6.1.11

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  modular_test: ^2.0.0
  triple_test: ^2.0.0

flutter_icons:
  ios: true
  android: "launcher_icon"
  image_path: "assets/images/cab.png"

flutter:

  uses-material-design: true

  assets:
    - assets/error/
    - assets/images/
    - assets/background/
    - assets/lottie/
    - assets/profile/
    - assets/success/
    - .env
